# 异常处理

## 1、catch捕获异常

不会进行数据类型的默认转换

## 2、限制异常的方法

### 1、没有限制

`int f(int,char);//可以抛出任何异常`

### 2、throw参数表

在函数声明后添加throw参数表，指出可以抛出的异常类型

```cpp

int func(int,char);

throw(int,char);
```

### 3、throw空表

不允许抛出任何异常

```cpp
int func(int,char);

throw();
```

### 4、catch

- 多用于捕获某种特定异常

- 但也可用于捕获所有异常
  
  ```cpp
  catch(...)
  {
      //异常处理代码
  }
  ```

- catch再次抛出异常（自己无法处理）给外部的catch块，在catch异常处理语句中添加throw()可实现！
  
  ```cpp
  void Handler(int n)
  {
      try{
       if(n==1)
         throw n;
      }catch(int n){
        cout<<"Catch an exception inside!\n";
        throw(n) 
      }
  }
  //内部再次throw时，函数不能带throw
  int main()
  {
      try{
        Hanler(1);
      }catch(int n){
        cout<<"catch an exception in main!\n";
       }
  }
  ```

### 5、异常的嵌套调用

try块的嵌套->形成异常处理调用链

## 3、异常类

- 使用空类作为异常类，用throw和catch抛出和捕获；

- 使用base类和派生类来区分不同类型的异常

```cpp
BaseException->FileSysException->FileNotFind
int main()
{
    try
	{
		throw FileSysexception();
	}catch (FileNotFound p)
	{
		cout << p.Where() << endl;
	}catch (FileSysexception p)
	{
		cout << p.Where() << endl;
	}catch (BaseException p)
	{
		cout << p.Where() << endl;
	}
}
```

按照catch顺序捕获异常。
